# Generated by Django 3.2 on 2022-04-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='watchlist',
            new_name='watchlist_users',
        ),
    ]
